
-- connections:

MAIN_SERVER_IP = "127.0.0.1"
PORT = 5556

--

STARTUP_MONEY = 25

TRAIN_COST = 25

MONEY_PASSENGER = 5
MONEY_VIP = 15

CAM_ANGLE = -0.1

TRAIN_SPEED = 90
TRAIN_ACCEL = 1.2
MAX_BLOCK_TIME = 3

PASSENGER_SPEED = 110

GAME_TYPE = 1
GAME_TYPE_MAX_PASSENGERS = 1
GAME_TYPE_TIME = 2
ROUND_TIME = 1000

MAX_NUM_TRAINS = 5
MAX_NUM_PASSENGERS = 50

VIP_RATIO = 1/7
MAX_VIP_TIME = 30
MIN_VIP_TIME = 10

-- game options:

POSSIBLE_TIMES = {"Day", "Rushhour"}
POSSIBLE_MODES = {"Time", "Passengers"}

-- tutorial:

TUT_BOX_X = 25
TUT_BOX_Y = 75
CODE_BOX_X = 60
CODE_BOX_Y = 75

-- sizes:

STND_BUTTON_WIDTH = 150
STND_BUTTON_HEIGHT = 35

SMALL_BUTTON_WIDTH = 100
SMALL_BUTTON_HEIGHT = 28

TUT_BOX_WIDTH = 500
TUT_BOX_HEIGHT = 200

CODE_BOX_WIDTH = 350
CODE_BOX_HEIGHT = 200

BOX_STATUS_WIDTH = 200
BOX_STATUS_HEIGHT = 150

STAT_BOX_WIDTH = 350
STAT_BOX_HEIGHT = 95

STAT_MSG_WIDTH = 550
STAT_MSG_HEIGHT = 45

BUBBLE_WIDTH = 200
BUBBLE_HEIGHT = 75

--- colours:

BG_R = 50
BG_G = 30
BG_B = 20

CODE_BOX_R = 115
CODE_BOX_G = 115
CODE_BOX_B = 115

STAT_BOX_POSITIVE_R = 70
STAT_BOX_POSITIVE_G = 155
STAT_BOX_POSITIVE_B = 55

STAT_BOX_NEGATIVE_R = 150
STAT_BOX_NEGATIVE_G = 60
STAT_BOX_NEGATIVE_B = 40

STAT_BOX_STATUS_R = 150
STAT_BOX_STATUS_G = 150
STAT_BOX_STATUS_B = 150

BUTTON_OFF_R = 40
BUTTON_OFF_G = 110
BUTTON_OFF_B = 40

BUTTON_OVER_R = 90
BUTTON_OVER_G = 160
BUTTON_OVER_B = 90

--MSG_BOX_R = 55
--MSG_BOX_G = 65
--MSG_BOX_B = 45

MSG_BOX_R = 105
MSG_BOX_G = 135
MSG_BOX_B = 95

--HELP_BOX_R = 55
--HELP_BOX_G = 65
--HELP_BOX_B = 45

LOAD_BOX_SMALL_R = MSG_BOX_R - 20
LOAD_BOX_SMALL_G = MSG_BOX_G - 20
LOAD_BOX_SMALL_B = MSG_BOX_B - 20

LOAD_BOX_LARGE_R = MSG_BOX_R
LOAD_BOX_LARGE_G = MSG_BOX_G
LOAD_BOX_LARGE_B = MSG_BOX_B

STAT_MSG_R = MSG_BOX_R
STAT_MSG_G = MSG_BOX_G
STAT_MSG_B = MSG_BOX_B

STAT_ERR_R = 150
STAT_ERR_G = 60
STAT_ERR_B = 40

BUBBLE_R = 200
BUBBLE_G = 200
BUBBLE_B = 200

